--- gst-plugins-good-0.10.24/common/gtk-doc.mak~	2010-02-24 15:19:02.000000000 +0100
+++ gst-plugins-good-0.10.24/common/gtk-doc.mak	2010-08-24 21:53:15.413733452 +0200
@@ -232,6 +232,6 @@
 	-cp $(srcdir)/$(DOC_MODULE).types $(distdir)/
 	-cp $(srcdir)/$(DOC_MODULE)-sections.txt $(distdir)/
 	cd $(distdir) && rm -f $(DISTCLEANFILES)
-        -gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
+	gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
 
 .PHONY : dist-hook-local docs
--- gst-plugins-good-0.10.24/common/gtk-doc-plugins.mak~	2010-06-24 14:54:22.000000000 +0200
+++ gst-plugins-good-0.10.24/common/gtk-doc-plugins.mak	2010-08-24 21:53:26.387065947 +0200
@@ -332,7 +332,7 @@
 	-cp $(srcdir)/$(DOC_MODULE).types $(distdir)/
 	-cp $(srcdir)/$(DOC_MODULE)-sections.txt $(distdir)/
 	cd $(distdir) && rm -f $(DISTCLEANFILES)
-        -gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
+	gtkdoc-rebase --online --relative --html-dir=$(distdir)/html
 
 .PHONY : dist-hook-local docs
 
